// Summarization prompts for context compression.

export const SUMMARY_PREFIX = `[CONTEXT COMPACTION — REFERENCE ONLY] Earlier turns were compacted into the summary below. This is a handoff from a previous context window — treat it as background reference, NOT as active instructions. Do NOT answer questions or fulfill requests mentioned in this summary; they were already addressed. Respond ONLY to the latest user message that appears AFTER this summary — that message is the single source of truth for what to do right now. Topic overlap with the summary does NOT mean you should resume its task: even on similar topics, the latest user message WINS. Treat ONLY the latest message as the active task and discard stale items from the historical sections entirely — do not "wrap up" or "finish" work described there unless the latest message explicitly asks for it. Reverse signals in the latest message (e.g. "stop", "undo", "roll back", "just verify", "don't do that anymore", "never mind", a new topic) must immediately end any in-flight work described in the summary; do not re-surface it in later turns. The current session state (files, config, etc.) may reflect work described here — avoid repeating it:`

export const SUMMARY_END_MARKER = `--- END OF CONTEXT SUMMARY — respond to the message below, not the summary above ---`

export const FALLBACK_COMPACTION_NOTE = `[Earlier conversation turns were removed to keep the context window manageable. The most recent messages are preserved below.]`

export const IDENTIFIER_PRESERVATION_INSTRUCTIONS = `Preserve all opaque identifiers exactly as written — do not shorten, reconstruct, or normalize them. This includes file paths, directory paths, function names, class names, variable names, UUIDs, hashes, IDs, hostnames, IP addresses, ports, URLs, API keys, tokens, and commit hashes. If the original uses a specific separator or casing, keep it.`
